import { EvoItem } from '../item';
import { EvoItemRestictions } from '../../restrictions';
import { EvoRarity } from '../../rarity';

export const alterEgoItems: { [id: string]: EvoItem } = {
  'Ascended Light of Destiny': {
    id: 'Ascended Light of Destiny',
    restriction: EvoItemRestictions.TANK,
    rarity: EvoRarity.MYTHIC,
    icon: 'AscendedLightOfDestiny',
    description: 'The final evolution of the Light of Destiny. By manifesting the energies of thousands of evil, the axe has transcended to its peak power. Unstable at first and was forged with Sealing Aura to prevent from shattering, Artix taught the hero how to use his mastercraft.',
    effects: [
      '+3000 Damage',
      '+300 Armor',
      'Active: Blinds all nearby enemies for 2.5 seconds and heals the user for 20% of missing HP. Cooldown 50s.',
    ],
    crafting: [
      'Blinding Light of Destiny',
      'Golden Fragment' ,
      'Light Synthesis',
      'Mystical' ,
      'Fire Stone',
      'Angelic Hope',
      ],
      source: 'Alter Ego',
  },
  'Cane of Byrna': {
    id: 'Cane of Byrna',
    restriction: EvoItemRestictions.INT,
    rarity: EvoRarity.MYTHIC,
    icon: 'CaneOfByrna',
    description: "Like the Cane of Somaria, its origin is also unknown. But they say it may have been carried by a Hero during the Battle of a Thousand Heroes and later discovered by the Nords of Morwitijaal and Mad God Passage. The Cane was likely used in battle by said Nords, but ultimately hidden away.",
    effects: [
      '+1025 Intelligence',
      '+100 HP Regeneration',
      '+80 Mana Regeneration',
      '+15% Cooldown Reduction',
      'Active: Heals target\'s HP for (15,000 +12% Max HP) and provide 150 Armor for 5 seconds. Heals and buffs nearby allies for 50% of the amount. Cooldown 15s.',
    ],
    crafting: [
      'Dreaded Totem',
      'Nature Fragment' ,
      'Emerald',
      'Dragon Tooth' ,
      'Dragon Stone',
      'Angelic Hope',
      ],
      source: 'Alter Ego',
  },
  'Crisis Core': {
    id: 'Crisis Core',
    restriction: EvoItemRestictions.ALL_CLASSES,
    rarity: EvoRarity.MYTHIC,
    icon: 'CrisisCore',
    description: "The impure soul of the cruel world. Contained in the orb is the essence of the angel turned evil because of mankind's thirst for power. With this contains all the memories of the fallen angel and all the crises during the battle for the Golden Power.",
    effects: [
      '+550 All stats',
      '+25% Cooldown Reduction',
    ],
    crafting: [
      'Heart of Behemoth',
      'Harbinger\'s Heart' ,
      'Blessing of Dragon',
      'Sphere of Doom',
      'Dragon Stone',
      'Angelic Hope',
      ],
      source: 'Alter Ego',
  },
  'Consecration': {
    id: 'Consecration',
    restriction: EvoItemRestictions.ARCHER,
    rarity: EvoRarity.MYTHIC,
    icon: 'Consecration',
    description: "The impure soul of the cruel world. Contained in the orb is the essence of the angel turned evil because of mankind's thirst for power. With this contains all the memories of the fallen angel and all the crises during the battle for the Golden Power.",
    effects: [
      '+5500 Damage',
      '+25% Attack speed',
      '+25% BD',
      'Passive: Third basic attack deals (9,000 + 45% Agi) Pure Damage in an AOE and reduces armor by 20 for 1.5 seconds. Deals 250% against non-bosses.'
    ],
    crafting: [
      'Soulshot',
      'Diamond',
      'Mystical',
      'Dragon Stone',
      'Fire Stone',
      'Angelic Hope',
      ],
      source: 'Alter Ego',
  },
  "Drakath's Armor": {
    id: "Drakath's Armor",
    restriction: EvoItemRestictions.MELEE,
    rarity: EvoRarity.MYTHIC,
    icon: 'DrakathsArmor',
    description: "The armor of the forsaken Champion of Chaos. Made with all the artifacts from the 13 Lords of Chaos, the chaos reigns eternal.",
    effects: [
      '+450 Armor',
      'Passive: -17.5% Damage Taken from Attacks.',
      'Passive: Gains immolation that deals 12,500 Magic DPS to all nearby enemies.'
    ],
    crafting: [
      'Demonforge Plate',
      'Amethyst',
      'Blessing of Darkness',
      'Sphere of Doom',
      'Fire Rising',
      'Angelic Hope',
      ],
      source: 'Alter Ego',
  },
  "Eliot": {
    id: "Eliot",
    restriction: EvoItemRestictions.CHUNIN,
    rarity: EvoRarity.MYTHIC,
    icon: 'Eliot',
    description: "Named after the assassinator of the Great Archangel, the blade possesses zealot energies able to adapt greatly when used in combat. The blade's carries no weight while held, but transforms to heavy zealot blades once it touches the target's body.",
    effects: [
      '+1425 Agility',
      '+15% Cooldown Reduction',
      'Hunter:  Spellcast deals (5,000 + 25% Agi) Pure Damage to all nearby enemies. Deals 200% against non-bosses. Has a chance to proc Zealot Blast instead.',
      'Zealot Blast(P): Deals (15,000 + 75% Agi) Pure Damage to all nearby enemies. Deals 200% against non-bosses.',
    ],
    crafting: [
      'Nightshadow',
      'Golden Fragment',
      'Dragon Tooth',
      'Dragon Stone',
      'Fire Stone',
      'Angelic Hope',
      ],
      source: 'Alter Ego',
  },
  "Moon Pearl": {
    id: "Moon Pearl",
    restriction: EvoItemRestictions.ALL_CLASSES,
    rarity: EvoRarity.MYTHIC,
    icon: 'MoonPearl',
    description: "A shining gem which protects the hero from Ganon's magic, allowing to retain his normal shape while in the Dark World. Other humans entering the Dark World are transformed into shapes which reflect their \"True Nature\", or personality.",
    effects: [
      '+22 500 Health',
      '0.3% Max HP regen per second',
      '+40% Spell resistance',
     ],
    crafting: [
      'Starlight Crystal',
      'Harbinger\'s Heart',
      'Sphere of Doom',
      'Dragon Stone',
      'Fire Stone',
      'Angelic Hope',
      ],
      source: 'Alter Ego',
  },
  "Necrotic Sword of Doom": {
    id: "Necrotic Sword of Doom",
    restriction: EvoItemRestictions.MELEE_AGI,
    rarity: EvoRarity.MYTHIC,
    icon: 'NecroticSwordOfDoom',
    description: "Used by the King of the Undead, the blade's darkness compels... DOOOOOOOOOOOM!!!. Made from Doom's Heart and a thousand Void Auras, this blade enhances the wielder's undying will, embracing the death it delivers to its enemies.",
    effects: [
      '+4800 Damage',
      '+800 Agility',
      'Passive: Increase Physical Damage up to 12% based on Current MP.',
      'Passive: Basic attack deals 80,000 Bonus Pure Damage and slows the target by 99% for 0.75 seconds. Cooldown 12s.'
    ],
    crafting: [
      'Cursed Blade',
      "Harbinger's Heart",
      'Blessing of Darkness',
      'Sphere of Doom',
      'Fire Stone',
      'Angelic Hope',
    ],
    source: 'Alter Ego',
  },
  "Sinister Staff": {
    id: "Sinister Staff",
    restriction: EvoItemRestictions.INT,
    rarity: EvoRarity.MYTHIC,
    icon: 'SinisterStaff',
    description: "The staff used by cult leaders upon performing deadly rituals. Often using humans as sacrificial lambs to create a link that allows wicked people to envelop their inner demons.",
    effects: [
      '+1550 Intelligence',
      '+10% Cooldown Reduction',
      'Passive: Spellcast grants 1 Stack, at 3 Stacks, the next basic attack deals (16,000 + 80% Int) Pure Damage in a huge area. Main target takes 150% damage.'
    ],
    crafting: [
      'Destruction',
      'Ruby',
      'Harbinger\'s Essence',
      'Sphere of Doom',
      'Fire Stone',
      'Angelic Hope',
    ],
    source: 'Alter Ego',
  },
  "Sword of Akasha": {
    id: "Sword of Akasha",
    restriction: EvoItemRestictions.MELEE_AGI,
    rarity: EvoRarity.MYTHIC,
    icon: 'SwordOfAkasha',
    description: "Found in the World of C. It is commonly depicted as floating in billowing clouds with no land or sky in sight. This is revealed to be merely an illusion that hides the sword's true power, the power to kill the Gods.",
    effects: [
      '+1350 Agility',
      '+35% Attack Speed',
      'Passive: Each hit reduces enemy\'s armor by 1 for 5 seconds (Max: 20). Enemy with max stack gets extra 5 armor reduction and takes 5% more basic attack damage.'
    ],
    crafting: [
      'Malevolent',
      'Sphere of Doom',
      'Mystical',
      'Dragon Stone',
      'Fire Stone',
      'Angelic Hope',
    ],
    source: 'Alter Ego',
  },
  "Titan's Mitt": {
    id: "Titan's Mitt",
    restriction: EvoItemRestictions.MELEE,
    rarity: EvoRarity.MYTHIC,
    icon: 'TitansMitt',
    description: "Stolen by the Leader of Thieves, Blind has used this powerful gloves to break out of his cell and destroy the whole prison for his gang. It grants the strength to carry the heaviest objects and break the toughest of locks ever created.",
    effects: [
      '+3000 Damage',
      '+300 Armor',
      'Passive: Basic attack has a chance to deal 70% Max HP as Magic Damage to the target.'
    ],
    crafting: [
      'Dragon Steel',
      'Diamond',
      'Mantle of Darkness',
      'Draconic Trinity',
      'Fire Stone',
      'Angelic Hope',
    ],
    source: 'Alter Ego',
  },
  "Ungodly Reaper of Nulgath": {
    id: "Ungodly Reaper of Nulgath",
    restriction: EvoItemRestictions.MELEE_AGI,
    rarity: EvoRarity.MYTHIC,
    icon: 'UngodlyReaperOfNulgath',
    description: "A few have proven beyond a shadow of doubt of loyalty to the Fiend of the Underworld. For that he has crafted the reavers of destruction for his loyal servants. All will tremble before you when you wield this.",
    effects: [
      '+7200 Damage',
      'Passive: 80% chance to deal 3x Physical Damage.'
    ],
    crafting: [
      'Cruel Blade',
      'Sphere of Doom',
      'Mystery',
      'Mystical',
      'Fire Stone',
      'Angelic Hope'
    ],
    source: 'Alter Ego',
  },
};
