import { EvoItem } from '../item';
import { EvoItemRestictions } from '../../restrictions';
import { EvoRarity } from '../../rarity';

export const pieces: { [id: string]: EvoItem } = {
  'Rare Weapon Piece': {
    id: 'Rare Weapon Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.RARE,
    icon: 'WeaponPiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Mega Weapon Piece': {
    id: 'Mega Weapon Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.EPIC,
    icon: 'WeaponPiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Ultra Weapon Piece': {
    id: 'Ultra Weapon Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.LEGENDARY,
    icon: 'WeaponPiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Mythical Weapon Piece': {
    id: 'Mythical Weapon Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.GODLY,
    icon: 'WeaponPiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Dull Armor Piece': {
    id: 'Dull Armor Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.UNCOMMON,
    icon: 'ArmorPiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Rare Armor Piece': {
    id: 'Rare Armor Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.RARE,
    icon: 'ArmorPiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Mega Armor Piece': {
    id: 'Mega Armor Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.EPIC,
    icon: 'ArmorPiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Ultra Armor Piece': {
    id: 'Ultra Armor Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.LEGENDARY,
    icon: 'ArmorPiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Mythical Armor Piece': {
    id: 'Mythical Armor Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.GODLY,
    icon: 'ArmorPiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Rare Handle Piece': {
    id: 'Rare Handle Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.RARE,
    icon: 'HandlePiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Mega Handle Piece': {
    id: 'Mega Handle Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.EPIC,
    icon: 'HandlePiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Ultra Handle Piece': {
    id: 'Ultra Handle Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.LEGENDARY,
    icon: 'HandlePiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Mythical Handle Piece': {
    id: 'Mythical Handle Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.GODLY,
    icon: 'HandlePiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  },
  'Fabled Armor Piece': {
    id: 'Fabled Armor Piece',
    restriction: EvoItemRestictions.FORGE,
    rarity: EvoRarity.MYTHIC,
    icon: 'ArmorPiece',
    description: '',
    effects: [],
    crafting: [],
    source: 'Blacksmith',
  }
};
